model_base_dir=/home/ops/jupyter/语义/dataprocess/摘要-标题-图谱/内容理解/Lattice_Bert/
init_checkpoint=$model_base_dir"ptms/chinese_labert-lite-std-512/"
vocab_file=$init_checkpoint"vocab.txt"
data_dir=$model_base_dir"train_data/xie_2300"
labert_config_file=$init_checkpoint"labert_config.json"
lexicon_file=$init_checkpoint"lexicon.txt"
output_dir=$model_base_dir"model/xie2k3"
CUDA_VISIBLE_DEVICES="1,2" /home/ops/miniconda3/envs/qiushi/bin/python run_sequence_labeling_crf_labert.py \
        --init_checkpoint=$init_checkpoint \
        --data_dir=$data_dir \
        --labert_config_file=$labert_config_file \
        --lexicon_file=$lexicon_file \
        --vocab_file=$vocab_file \
        --task_name=ner \
        --use_named_lexicon=False \
        --do_train=true \
        --do_eval=true \
        --learning_rate=5e-5 \
        --num_train_epochs=40 \
        --output_dir=$output_dir \
        --train_batch_size=100 \
        --n_gpus=2 \
